# Generated by Django 3.1.7 on 2021-03-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='url',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='shortcut',
            field=models.CharField(max_length=10),
        ),
    ]
