# Generated by Django 3.1.7 on 2021-03-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuter', '0002_auto_20210309_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
