# Generated by Django 3.1.7 on 2021-03-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuter', '0003_auto_20210309_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'managed': False, 'verbose_name_plural': 'addresses'},
        ),
    ]
