# Generated by Django 3.1.7 on 2021-03-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuter', '0004_auto_20210309_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
    ]
