# Generated by Django 3.1.7 on 2021-03-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuter', '0005_auto_20210309_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='domain',
        ),
        migrations.AlterField(
            model_name='address',
            name='shortcut',
            field=models.CharField(max_length=40),
        ),
    ]
